import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // EXACT Stitch palette — divine temple agarbatti experience
      colors: {
        background: "#181305",
        surface: "#181305",
        "surface-dim": "#181305",
        "surface-bright": "#3f3928",
        "surface-variant": "#3b3424",
        "surface-tint": "#ffb4a8",
        "surface-container-lowest": "#120e03",
        "surface-container-low": "#211b0c",
        "surface-container": "#251f10",
        "surface-container-high": "#302919",
        "surface-container-highest": "#3b3424",
        "on-background": "#ede1c9",
        "on-surface": "#ede1c9",
        "on-surface-variant": "#e3beb8",
        outline: "#aa8984",
        "outline-variant": "#5a403c",
        primary: "#ffb4a8",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "primary-container": "#8b0000",
        "on-primary": "#690000",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#920703",
        "on-primary-container": "#ff907f",
        secondary: "#ffb77d",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "secondary-container": "#d97707",
        "on-secondary": "#4d2600",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        "on-secondary-container": "#432100",
        tertiary: "#f7bd48",
        "tertiary-fixed": "#ffdea6",
        "tertiary-fixed-dim": "#f7bd48",
        "tertiary-container": "#583e00",
        "on-tertiary": "#412d00",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-tertiary-container": "#dda632",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#b52619",
        "inverse-surface": "#ede1c9",
        "inverse-on-surface": "#36301f",

        // Legacy aliases (so existing classes elsewhere don't break)
        ink: { DEFAULT: "#ede1c9", muted: "#e3beb8" },
        brand: { DEFAULT: "#ffb4a8", hover: "#ffb77d", soft: "#251f10" },
        sun: { DEFAULT: "#f7bd48", soft: "#251f10" },
        brass: { DEFAULT: "#f7bd48", hover: "#ffb77d", soft: "#251f10" },
        ruby: "#ffb4a8",
        maroon: "#8b0000",
        emerald: "#b7ccb9",
        indigo: "#aa8984",
        border: "#5a403c",
        success: "#b7ccb9",
        danger: "#ffb4ab",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "container-max-width": "1200px",
        margin: "64px",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        display: ["var(--font-noto-serif)", "Noto Serif", "serif"],
        serif: ["var(--font-noto-serif)", "Noto Serif", "serif"],
        manrope: ["var(--font-manrope)", "Manrope", "sans-serif"],
        tamil: ["var(--font-catamaran)", "system-ui", "sans-serif"],
        "headline-xl": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "headline-lg": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "headline-md": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "body-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-sm": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "6px",
        md: "10px",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
